# Generated by Django 5.0.4 on 2024-04-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_logo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='url',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
